#---- Bioconda config ----
name: varcaller
channels:
  - conda-forge
  - bioconda
dependencies:
  - pigz
  - bwa=0.7.17
  - samtools>=1.10
  - mosdepth>=0.3.1
  - bcftools>=1.12
  - parallel
  - python=3.8
  - pip:
    - "--editable=git+https://github.com/tomarovsky/Biocrutch.git#egg=Biocrutch"
    - "--editable=git+https://github.com/tomarovsky/MACE.git#egg=MACE"
    - "--editable=git+https://github.com/mahajrod/MAVR.git#egg=MAVR"
    - "--editable=git+https://github.com/mahajrod/RouToolPa.git#egg=RouToolPa"
